---
name: PHPStan

on: [push, pull_request]

permissions: {}

jobs:
  phpstan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer:v2
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
